### ISSUE TITLE
Is selecting training data from a file possible?

### ISSUE THREAD

**Issue by Foxkami** [arrrrny/tesseract_ocr#12]
I don't want my app APK to be too big due to tesseract OCR training data in assets.
What I want to do is download the training data file from a server to  storage and the load it storage.

The docs seem to suggest it can only load from assets. If it's already not possible please add a feature to load training data from file storage. Thanks!

**Comment by arrrrny** [comment]
@Foxkami you are welcome to contribute. If you make a PR that supports this feature, It would ve great. Or maybe try to download it to your assets. It might work.
