### ISSUE TITLE
File path assert fail in extratText method

### ISSUE THREAD

**Issue by CJMki** [arrrrny/tesseract_ocr#17]
I am getting an assertion failure withing this method 
`  static Future<String> extractText(String imagePath, {String language}) async {
    assert(await File(imagePath).exists(), true);
    final String tessData = await _loadTessData();
    final String extractText = await _channel.invokeMethod('extractText', <String, dynamic>{
      'imagePath': imagePath,
      'tessData': tessData,
      'language': language,
    });
    return extractText;
  }`
flutter version - 
`Flutter 1.17.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8af6b2f038 (3 weeks ago) • 2020-06-30 12:53:55 -0700
Engine • revision ee76268252
Tools • Dart 2.8.4`
App is running on debug mode

**Comment by vivian-ng** [comment]
Sorry for digging this up, I am getting a assert error too, how to solve this?
