### ISSUE TITLE
some suggestions

### ISSUE THREAD

**Issue by tygm** [arrrrny/tesseract_ocr#19]
1. The use of t.join() in Android native code will block the UI, causing the app to be stuck during recognition.
2.Provide the setvariable method of tessbaseapi to dart end.

Thanks to the plug-in author, I used it well in the project

**Comment by HTMHell** [comment]
> 1. The use of t.join() in Android native code will block the UI, causing the app to be stuck during recognition.
>    2.Provide the setvariable method of tessbaseapi to dart end.
> 
> Thanks to the plug-in author, I used it well in the project

do you have a solution to 1?
if so, can you provide a code snippet / pull request?
