### ISSUE TITLE
language financial makes 'Lost connection to device'

### ISSUE THREAD

**Issue by ssilb4** [arrrrny/tesseract_ocr#2]
using language eng works well.
after I change language financial, I get error 'Lost connection to device'

    final String extractText = await _channel.invokeMethod('extractText', <String, dynamic>{
      'imagePath': imagePath,
      'tessData': tessData,
      'language': language,
    });

after this function call, I got error.

android

flutter --version
Flutter 1.12.13+hotfix.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 27321ebbad (5 weeks ago) • 2019-12-10 18:15:01 -0800
Engine • revision 2994f7e1e6
Tools • Dart 2.7.0

**Comment by ssilb4** [comment]
maybe trained data was broken?

**Comment by arrrrny** [comment]
You shouldn't be changing that part, You are changing the core, You should use exactly as it is described inside example folder as :

text = await TesseractOcr.extractText(imagePath, language: "financial");

and make sure in your tessdata_config.json you have defined financial as:
{
  "files": [
    "eng.traineddata",
    "financial.traineddata"
  ]
}
