### ISSUE TITLE
Compiling for iOS 10.0, but module 'SwiftyTesseract' has a minimum deployment target of iOS 11.0

### ISSUE THREAD

**Issue by hasankarli** [arrrrny/tesseract_ocr#23]
My iOS deployment target 12 but I got this bug. How can I resolve this bug ?

**Comment by Lloyd666** [comment]
same issue +1

**Comment by hasankarli** [comment]
change this
`post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
`
to
`deployment_target = '12.0'
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
  installer.generated_projects.each do |project|
    project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = deployment_target
        end
    end
    project.build_configurations.each do |bc|
        bc.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = deployment_target
    end
  end
end
`
in Podfile
