### ISSUE TITLE
Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the classes and Android resources from any local .aar

### ISSUE THREAD

**Issue by bettkipronoh** [arrrrny/tesseract_ocr#25]
Hi, Thanks for the great library, 
I ran into this issue when i changed compiledSdk to 30. and added this to manifest
`<queries>-->
        <intent>-->
           <action android:name="android.speech.RecognitionService" />-->
       </intent>-->
    </queries>-->`
After that i was getting this error
 `Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the classes and Android resources from any local .aar`.
 For it to work i had to downgrade  Gradle plugin it to  3.5.1 while the current version is classpath 'com.android.tools.build:gradle:4.0.1’. 
Please Upgrade Android Gradle plugin and Update Gradle to avoid this error.

**Comment by shatanikmahanty** [comment]
I am also facing similar error

**Comment by bettkipronoh** [comment]
@shatanikmahanty I finally managed to solve this by changing classspath under `android\app\build.grandle` to 
`classpath 'com.android.tools.build:gradle:3.5.4'` and then changing this `distributionUrl=https\://services.gradle.org/distributions/gradle-5.4.1-all.zip` to this `distributionUrl=https\://services.gradle.org/distributions/gradle-6.1.1-all.zip` inside grandle-wrapper.properties under `android\grandle\wrapper` . 

Now setting compileSdkVersion 30 has no issue anymore

**Comment by gitcloned** [comment]
would it be possible for you to share your changed build.gradle file.. I couldn't find any classpath in `android\app\build.gradle` file.

**Comment by HTMHell** [comment]
> would it be possible for you to share your changed build.gradle file.. I couldn't find any classpath in `android\app\build.gradle` file.

The correct file path is `android/build.gradle`
