### ISSUE TITLE
Execution failed for task ':tesseract_ocr:bundleDebugAar'.

### ISSUE THREAD

**Issue by ZdenekKrcal** [arrrrny/tesseract_ocr#28]
Hi, thank you for package but pleas coud you give support for Flutter 2 and web support? 

I cant use that package because of that problem:

Launching lib\main.dart on sdk gphone x86 in debug mode...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':tesseract_ocr:bundleDebugAar'.
> Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the classes and Android resources from any local .aar file dependencies would not be packaged in the resulting AAR. Previous versions of the Android Gradle Plugin produce broken AARs in this case too (despite not throwing this error). The following direct local .aar file dependencies of the :tesseract_ocr project caused this error: C:\flutter_dev\flutter\.pub-cache\hosted\pub.dartlang.org\tesseract_ocr-0.3.1\android\libs\tesseract4android-release.aar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by arrrrny** [comment]
open for contributions. not planning any time soon.
