### ISSUE TITLE
Direct local .aar file dependencies are not supported when building an AAR.

### ISSUE THREAD

**Issue by ZdenekKrcal** [arrrrny/tesseract_ocr#29]
Please update gradle in plugin.

I ran into this issue when i changed compiledSdk to 30. and added this to manifest
<queries>--> <intent>--> <action android:name="android.speech.RecognitionService" />--> </intent>--> </queries>-->
After that i was getting this error
Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the classes and Android resources from any local .aar.

**Comment by ParthParekh-dev** [comment]
How did you solve this? I am facing the same issue.

**Comment by ZdenekKrcal** [comment]
Hi, I think everything works when you downgrade version of gradle in android to version 3.5. But it is not nice solution because flutter will come with newer versions. This package is not updated and it would be nice if someone else create new package.
