### ISSUE TITLE
OCR does not extract full text. 

### ISSUE THREAD

**Issue by osmansorkar** [arrrrny/tesseract_ocr#3]
I had OCR bottom image. 
![test](https://user-images.githubusercontent.com/10289018/74222480-d187a580-4cde-11ea-8e36-b1400b99e030.png)
I had got this result . 
![Screenshot_5](https://user-images.githubusercontent.com/10289018/74222518-e6fccf80-4cde-11ea-9ca0-0d8cb2ebe806.png)

It is missing 4 line bottom. Every time when I give big image. it missing some text. Is there any word limit has on this plugin??

**Comment by TheLastGimbus** [comment]
How did it came out? Is it working again?
