### ISSUE TITLE
Error while building, AAR dependencies

### ISSUE THREAD

**Issue by hazem-saeed** [arrrrny/tesseract_ocr#33]
While building the app after installing, this error is thrown:-

> Execution failed for task ':tesseract_ocr:bundleDebugAar'.
> Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the classes and Android resources from any local .aar file dependencies would not be packaged in the resulting AAR. Previous versions of the Android Gradle Plugin produce broken AARs in this case too (despite not throwing this error). The following direct local .aar file dependencies of the :tesseract_ocr project caused this error: C:\Flutter\.pub-cache\hosted\pub.dartlang.org\tesseract_ocr-0.3.1\android\libs\tesseract4android-release.aar

Please advise on how to solve this. Thanks.

**Comment by ParthParekh-dev** [comment]
Have you found any solution?

**Comment by hazem-saeed** [comment]
> 
> 
> Have you found any solution?

try this:-
https://stackoverflow.com/questions/65093701/flutter-plugin-that-uses-aar-modules-builds-and-runs-fine-in-the-example-app-bu

**Comment by igorferro1** [comment]
> > Have you found any solution?
> 
> try this:-
> https://stackoverflow.com/questions/65093701/flutter-plugin-that-uses-aar-modules-builds-and-runs-fine-in-the-example-app-bu

This one didn't work for me, did it work for you? I'm still having the same issue

**Comment by hazem-saeed** [comment]
> 
> 
> > > Have you found any solution?
> > 
> > 
> > try this:-
> > https://stackoverflow.com/questions/65093701/flutter-plugin-that-uses-aar-modules-builds-and-runs-fine-in-the-example-app-bu
> 
> This one didn't work for me, did it work for you? I'm still having the same issue

Yes it did. But I dropped using this package entirely, the ocr didn't work properly.

**Comment by igorferro1** [comment]
> > > > Have you found any solution?
> > > 
> > > 
> > > try this:-
> > > https://stackoverflow.com/questions/65093701/flutter-plugin-that-uses-aar-modules-builds-and-runs-fine-in-the-example-app-bu
> > 
> > 
> > This one didn't work for me, did it work for you? I'm still having the same issue
> 
> Yes it did. But I dropped using this package entirely, the ocr didn't work properly.

Got it. If I may ask, which solution did you use instead of tesseract?

**Comment by hazem-saeed** [comment]
> 
> 
> > > > > Have you found any solution?
> > > > 
> > > > 
> > > > try this:-
> > > > https://stackoverflow.com/questions/65093701/flutter-plugin-that-uses-aar-modules-builds-and-runs-fine-in-the-example-app-bu
> > > 
> > > 
> > > This one didn't work for me, did it work for you? I'm still having the same issue
> > 
> > 
> > Yes it did. But I dropped using this package entirely, the ocr didn't work properly.
> 
> Got it. If I may ask, which solution did you use instead of tesseract?

I didn't find any replacement yet. I'm either going to create the ocr on the server by using python, or I'm going to re-write this package from the ground up.

**Comment by arrrrny** [comment]
@hazem-saeed It would be great if you build from ground up.  I released this package more than a year ago When I needed ocr for my project. Google released Mlvision. Detached it from firebase. So no firebase account needed.  I recommend using that. I dont have time to update this package, I am not using it anymore.
