### ISSUE TITLE
Other language not working ?

### ISSUE THREAD

**Issue by jedsada-jed** [arrrrny/tesseract_ocr#4]
Hello, 

I try to thai language. But i found problem  as below.

![220488](https://user-images.githubusercontent.com/21008002/74599847-28182980-50bb-11ea-85ee-a93652364834.jpg)

I am sure for correct setting.

<img width="432" alt="Screen Shot 2563-02-16 at 12 45 59" src="https://user-images.githubusercontent.com/21008002/74599870-8e04b100-50bb-11ea-91a7-b8759423d829.png">

<img width="447" alt="Screen Shot 2563-02-16 at 12 47 16" src="https://user-images.githubusercontent.com/21008002/74599871-90670b00-50bb-11ea-938a-65851068a59b.png">

I download `tha.traineddata` from here
https://github.com/tesseract-ocr/tessdata_best/blob/master/tha.traineddata

Thank you

**Comment by arrrrny** [comment]
You set the language: currently it is set to financial:(numbers) set it to "tha"

extractText = await TesseractOcr.extractText(imagePath, language: "tha");

<img width="334" alt="Screen Shot 2020-02-17 at 3 48 20 PM" src="https://user-images.githubusercontent.com/48218623/74655194-04c5ab00-519d-11ea-8f76-bc4ce72138b0.png">

**Comment by jedsada-jed** [comment]
Oh, Thank you.

**Comment by xiechunyan** [comment]
Did you report 'flutter Could not initialize Tesseract API with language=eng' when using this plugin?

**Comment by narate1973** [comment]
Can i use use it multilingual?
