### ISSUE TITLE
it does not work on real mobile

### ISSUE THREAD

**Issue by aberciozhang** [arrrrny/tesseract_ocr#5]
Use example convert to apk , but apk doesn't  work . it exit right now !
Tks!

**Comment by PCuliar** [comment]
I found out when running the flutter-ocr-demo using language:financial it is working on android-device, iOS-device and iOS-simulator. when setting language:eng, it is working on android-device and on iOS-simulator but crashing on iOS-device (iPhone).

My investigation lead me to following exception:
//ios Thread 1: Fatal error: Initialization of SwiftyTesseract has failed. Check that the tessdata folder has been added to the project as a folder reference and contains the correct .traineddata files for the specified engine mode and language(s).
//ios Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory.

i tried adding a tessdata-folder in xcode containing the trained data-files but this did not help.

i guess it must be solvable by setting a simple value somewhere but i am new to flutter, so if anyone already did solve this, please post here :)

**Comment by arrrrny** [comment]
@PCulia open your Podfile and add  platform :ios, '10.0' to the top 
then go to ios folder on your project and run pod install.
